export const ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  PENDING: 'PENDING',
};

export const COURSE_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
};

export const COURSE_LEVEL = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
};

export const PAYMENT_METHOD = {
  VISA: 'VISA',
  MASTERCARD: 'MASTERCARD',
  KNET: 'KNET',
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  STRIPE: 'STRIPE',
  PAYPAL: 'PAYPAL',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const EXAM_TYPE = {
  MCQ: 'MCQ',
  TRUE_FALSE: 'TRUE_FALSE',
  ESSAY: 'ESSAY',
};

export const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

export const NOTIFICATION_TYPE = {
  COURSE: 'COURSE',
  EXAM: 'EXAM',
  PAYMENT: 'PAYMENT',
  SYSTEM: 'SYSTEM',
  GENERAL: 'GENERAL',
};



